import { readFile, writeFile, mkdir, copyFile } from "node:fs/promises";
import { createHash } from "node:crypto";
const source="android-app/app/build/outputs/apk/debug/app-debug.apk";
const apk=await readFile(source);
if(apk.length < 100000 || apk.readUInt32LE(0)!==0x04034b50) throw Error("Compila primero un APK Android real con :app:assembleDebug.");
await mkdir("output/entrega-final",{recursive:true});
const name="Truec-app-1.3.0-demo.apk";
await copyFile(source,"output/entrega-final/"+name);
const hash=createHash("sha256").update(apk).digest("hex");
await writeFile("output/entrega-final/"+name+".sha256",hash+"  "+name+"\n");
await writeFile("release/RELEASE_REPORT.md","# Artefacto de demostración\n\nAPK real generado con Gradle, variante debug, paquete com.truecapp.mobile.demo. Firma de desarrollo; no es un release de producción.\n\nTamaño: "+apk.length+" bytes.\n\nSHA-256: "+hash+"\n\nSalida: output/entrega-final/"+name+".\n\nLa simulación de Google Play es un recorrido académico; no sube archivos ni instala aplicaciones. Las pruebas se documentan en docs/validacion-final.\n");
console.log("APK real copiado y checksum calculado:",hash);
